### ISSUE TITLE
Add autoconnect-retries-default to NetworkManager configs.

### ISSUE THREAD

**Issue by bflanagin** [pop-os/default-settings#110]
## Enhancement

Currently NetworkManager is set to fail after 4 attempts to auto-connect to a prefigured wifi connection. In rare occasions this may not be enough to ensure the computer reconnects after a power failure or other event. We should consider setting the auto-connect retry value to something higher than 4 to ensure proper reconnects.

## Issue 
https://github.com/pop-os/pop/issues/1490

Create file `/etc/NetworkManager/conf.d/pop_os-autoconnect` (filename could be better) and insert the following lines:
```
[main]
autoconnect-retries-default = 10

```

**Comment by jacobgkau** [comment]
Creating the configuration file that you're describing does not solve the issue described in https://github.com/pop-os/pop/issues/1490. I'm still able to replicate a disconnection by turning off a hotspot, and the connection does not automatically re-connect after turning the hotspot back on. (This is Pop!_OS 20.10 on a galp5.)

**Comment by jacobgkau** [comment]
We triaged this issue to the NetworkManager version in https://github.com/pop-os/pop/issues/1490. A newer NetworkManager version works properly (without changing any configuration.)

Since this configuration change doesn't fix the issue, I'm closing this PR for now.
