### ISSUE TITLE
Bluetooth activates automatically after turning on Pc after suspension

### ISSUE THREAD

**Issue by OsmosisJones11m** [pop-os/default-settings#143]
Pop_Os! 22.04 LTS on Dell Inspiron 15 5510
 
 
Bluetooth

Nine times on ten Bluetooth activates automatically after turning on Pc after suspension

**Comment by n3m0-22** [comment]
Just to clarify, are you turning off bluetooth then suspending and then it's turning itself back on after resuming?

**Comment by OsmosisJones11m** [comment]
> Just to clarify, are you turning off bluetooth then suspending and then it's turning itself back on after resuming?

Yes, the bluetooth it's off when I suspend the PC, then I resume and it activates alone.

**Comment by n3m0-22** [comment]
Thank you for confirming. I am seeing this happen as well.
