### ISSUE TITLE
Bluetooth off after waking from suspend 22.04

### ISSUE THREAD

**Issue by jravetch** [pop-os/default-settings#158]
With bluetooth on, I enable suspend.  After waking from suspend bluetooth is off, I need to turn it back on.  I see the same issue was fixed for 20.04 now it's happening in 22.04 #147.  I'm on a Dell XPS 13 7390.

**Comment by RW21** [comment]
Yep. Can confirm that it is happening.
I'm on a Dell XPS 15 9500, 22.04.

Strange that when I run `lib/systemd/system-sleep/pop-default-settings_bluetooth-suspend` from bash, it works fine. 
However if it runs when my machine resumes from sleep, it does run, but bluetooth does not get unblocked.

I also checked that this line does actually run.
```bash
[ ! -f "$BT_BLOCK_PATH" ] && rfkill unblock bluetooth
```

Other things I checked:
- logs in ` journalctl -b -u systemd-suspend.service` 
  - Nothing
- Permissions
  - I set a+rwx.

The script is working completely as intended, but perhaps something else is preventing bluetooth from unblocking?

**Comment by RW21** [comment]
For the moment, I emptied the script. 
Bluetooth does not get unblocked when suspended, but that is fine for me.

**Comment by jravetch** [comment]
Clearing the script does enable bluetooth upon waking from suspend, but my devices no longer autoconnect.  Unblocking is required for my bluetooth mouse to connect.

**Comment by jackpot51** [comment]
This sounds to me like a timing issue. Perhaps adding a sleep to the script would help?

We may be able to remove this script now, if the Linux regression requiring it is fixed. I am hesitant to do that, however, in case the regression comes back.

**Comment by jravetch** [comment]
What was the regression that made this an issue?  I'm fine with keeping the script as long as it does what it's intended.  Where should I put the sleep?

**Comment by jackpot51** [comment]
The regression is that a number of bluetooth controllers broke suspend with kernels 5.18 and newer. This script just turns them off prior to suspend, and back on after. A sleep before the rfkill unblock bluetooth command would work.

**Comment by jackpot51** [comment]
`[ ! -f "$BT_BLOCK_PATH" ] && sleep 1 && rfkill unblock bluetooth` will sleep 1 second before trying to unblock bluetooth. Adjust the `1` up if it does not work until you have a good value.

**Comment by jravetch** [comment]
That worked perfectly!  Thank you so much!  Can I submit a pull request to add the sleep here https://github.com/pop-os/default-settings/blob/master_jammy/lib/systemd/system-sleep/pop-default-settings_bluetooth-suspend#L22 ?

**Comment by jackpot51** [comment]
Absolutely. We will then have to put it through extensive QA to ensure there are no regressions.

**Comment by backmeupplz** [comment]
Hmm it seems to still happen to me on ThinkPad X1 Carbon gen 10 and 22.04

**Comment by tvanesse** [comment]
Same here on ThinkPad X1 Carbon and 22.04 as well.
