### ISSUE TITLE
Properly name Pop!_OS iso test releases

### ISSUE THREAD

**Issue by brs17** [pop-os/default-settings#32]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Issue/Bug Description**
Change VERSION and PRETTY NAME of Pop!_OS 18.04 appropriately when releasing testing isos.

**Expected behavior**
When releasing test isos the name(PRETTY NAME) should be something along the lines of `Pop!_OS 18.04 LTS (Testing)` or `Pop!_OS 18.04 LTS (Test release)` or something along those lines.

VERSION should probably be something like `18.04 LTS (Testing)`

**Comment by brs17** [comment]
@WatchMkr If you have better phrasing or like one way better than the other let us know

**Comment by jackpot51** [comment]
This was finished in https://github.com/pop-os/default-settings/commit/0859e0f3e75019ad7111e52b39004249d29cb7e7
