### ISSUE TITLE
Set correct version name for Pop!_OS 18.04 final release

### ISSUE THREAD

**Issue by brs17** [pop-os/default-settings#33]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Issue/Bug Description**
When creating the first 18.04 iso for release, change VERSION to `18.04 LTS` and PRETTY NAME to `Pop!_OS 18.04 LTS`

**Comment by jackpot51** [comment]
This was fixed in https://github.com/pop-os/default-settings/commit/0859e0f3e75019ad7111e52b39004249d29cb7e7

**Comment by brs17** [comment]
This PR is for after we are done with test releases to remove the `(Testing)` part of the name. This will stay open till then, no?

**Comment by jackpot51** [comment]
K
