### ISSUE TITLE
please drop wayland, use xorg by default again

### ISSUE THREAD

**Issue by sudopluto** [pop-os/default-settings#37]
I noticed a recent update here that reenabled wayland.

Ubuntu is sticking with Xorg for this release, and I feel that pop should do the same.

There are tons of issues, like gnome not starting on nvidia cards, poor performance from gnome, and complications in optimus systems.

**Comment by jackpot51** [comment]
Xorg is the default

**Comment by sudopluto** [comment]
https://github.com/pop-os/default-settings/blob/master_bionic/etc/pop-os/gdm3/custom.conf

shouldn't line number 7 be uncommented? that's what I had to do to get my nvidia based system to login.

**Comment by jackpot51** [comment]
This configuration file matches the Ubuntu one exactly. This allows the Wayland session, but does not default to it. You should be able to select the session type with the gear next to the Sign In button when you are logging in.
