### ISSUE TITLE
App-folders

### ISSUE THREAD

**Issue by OliverScholtz** [pop-os/default-settings#39]
Java in System, Totem (Video????) out of the folder... more issues in System and Utliities --->

****************************************************
#!/bin/sh

APP_FOLDER="org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Pop"

gsettings reset-recursively "${APP_FOLDER}-Office/"
gsettings set "${APP_FOLDER}-Office/" name "Office.directory"
gsettings set "${APP_FOLDER}-Office/" translate true
gsettings set "${APP_FOLDER}-Office/" apps "[
'libreoffice-calc.desktop',
'libreoffice-draw.desktop',
'libreoffice-impress.desktop',
'libreoffice-math.desktop',
'libreoffice-startcenter.desktop',
'libreoffice-writer.desktop'
]"

gsettings reset-recursively "${APP_FOLDER}-System/"
gsettings set "${APP_FOLDER}-System/" name "System.directory"
gsettings set "${APP_FOLDER}-System/" translate true
gsettings set "${APP_FOLDER}-System/" apps "[
'gnome-language-selector.desktop',
'gnome-session-properties.desktop',
'gnome-system-monitor.desktop',
'im-config.desktop',
'nvidia-settings.desktop',
'org.gnome.baobab.desktop',
'org.gnome.DiskUtility.desktop',
'org.gnome.PowerStats.desktop',
'seahorse.desktop',
'software-properties-gnome.desktop',
'system76-driver.desktop',
'gtkorphan.desktop',
'JB-jconsole-jdk8.desktop',
'JB-mission-control-jdk8.desktop',
'JB-controlpanel-jdk8.desktop',
'JB-policytool-jdk8.desktop',
'JB-jvisualvm-jdk8.desktop',
'JB-javaws-jdk8.desktop',
'ca.desrt.dconf-editor.desktop',
'org.gnome.Software.desktop',
'ubuntu-cleaner.desktop'
]"

gsettings reset-recursively "${APP_FOLDER}-Utility/"
gsettings set "${APP_FOLDER}-Utility/" name "X-GNOME-Utilities.directory"
gsettings set "${APP_FOLDER}-Utility/" translate true
gsettings set "${APP_FOLDER}-Utility/" apps "[
'com.github.donadigo.eddy.desktop',
'eog.desktop',
'evince.desktop',
'file-roller.desktop',
'gucharmap.desktop',
'org.gnome.font-viewer.desktop',
'org.gnome.Screenshot.desktop',
'popsicle.desktop',
'simple-scan.desktop',
'dropbox.desktop',
'yelp.desktop',
'gnome-control-center.desktop',
'org.gnome.tweaks.desktop'
]"

gsettings reset org.gnome.desktop.interface scaling-factor
****************************************************

This tweak makes Gnome-Extentions like "App-Folders" unuseable.

Maybe delete this Bash and let it all as default. If we want make folders, we install the Extention.

**Comment by brs17** [comment]
Applications were sorted into folders in a way we believe helps organize different types of programs. With GNOME 3.34, users can now drag and drop to create new folders and move applications around, so this should no longer be an issue.
