### ISSUE TITLE
Automatic suspend on battery is set to 20 minutes

### ISSUE THREAD

**Issue by brs17** [pop-os/default-settings#48]
The "Automatic Suspend" feature is currently enabled by default on battery power for 20 minutes. It is desired to disable this feature out of the box.

**Comment by jackpot51** [comment]
@brs17 check the /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type settings:

```
dconf read /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
```

It should be empty if it is set to the default.

```
gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type
```

It should return this:

```
'nothing'
```

**Comment by brs17** [comment]
@jackpot51 I get exactly what you described: blank output from 

`dconf read /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type`

and `nothing` from

`gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type`

**Comment by brs17** [comment]
Well I should be looking for `sleep-inactive-battery-type` instead...update coming soon.

**Comment by brs17** [comment]
So
 `dconf read /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type`
returns blank.

`gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type`
returns 'suspend'

**Comment by brs17** [comment]
I should have a pr to fix this shortly

**Comment by brs17** [comment]
Fixed by https://github.com/pop-os/default-settings/pull/51, https://github.com/pop-os/default-settings/pull/50, and https://github.com/pop-os/default-settings/pull/49
