### ISSUE TITLE
Use Pop!_OS as Distributor ID for LSB

### ISSUE THREAD

**Issue by brs17** [pop-os/default-settings#71]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 20.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
lsb_release

**Issue/Bug Description:**
For 20.04, add Pop!_OS specific lsb_release information so that the `Distributor ID` will be recognized uniquely as Pop!_OS.

**Comment by brs17** [comment]
When this is implemented, it will fix https://github.com/pop-os/system76-driver/issues/27

**Comment by brs17** [comment]
@jackpot51, Currently in 20.04, `lsb_release` and `/etc/os-release` return(respectively):

```
Distributor ID:	Pop
Description:	Pop!_OS 20.04
Release:	20.04
Codename:	focal
```
```
NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

The system76-driver now lists the operating system as `Pop 20.04` where it should say `Pop!_OS 20.04`.

**Comment by jackpot51** [comment]
We can't have an exclamation in lsb_release unfortunately so I would feel fine with Pop 20.04 in system76-driver or patch it to use os-release

This particular issue is fixed
