### ISSUE TITLE
Add "LTS" Pop!_OS 20.04 name

### ISSUE THREAD

**Issue by brs17** [pop-os/default-settings#82]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 20.04 

**Issue/Bug Description:**
Currently the output of `lsb_release -a` has a "Description: " of "Pop!_OS 20.04". This description should say "Pop!_OS 20.04 LTS"

Similarly the PRETTY_NAME shown in /etc/os-release is "Pop!_OS 20.04". It should also say Pop!_OS 20.04 LTS".

**Comment by jackpot51** [comment]
Fixed in https://github.com/pop-os/default-settings/commit/cb416b9fba2724891c66a9cb4d84a65bafc44d5d
